#!/bin/bash

if [ $UID -ne 0 ]; then
   echo "You must be root to run this!"
   exit
fi 

# Find out where files are located
source config
source $GEMSTONE_CONFIG

echo "This script stops all Gemstone processes and removes all GemStone logs."
ls $GEMSTONE_LOGDIR

echo "Shall I continue? (Y/N)"

read cont
case "$cont" in
    y|Y|yes)
    ;;
    *)
    echo "Not continuing"
    exit
    ;;
esac

/etc/init.d/topaz stop 1 > /dev/null
/etc/init.d/gemstone stop 1 > /dev/null
/etc/init.d/netldi stop 1 > /dev/null

rm -f $GEMSTONE_LOGDIR/*

# Success
exit 0
