#!/bin/bash

if [ $UID -ne 0 ]; then
   echo "You must be root to run this!"
   exit
fi 

# Find out where files are located
source config
source $GEMSTONE_CONFIG

echo "`basename $0` copies modified Seaside scripts to $GEMSTONE/seaside/bin"
echo "They do not overwrite existing scripts, as they have different names."
echo "Shall I continue? (Y/N)"

read cont
case "$cont" in
    y|Y|yes)
    ;;
    *)
    echo "Not continuing"
    exit
    ;;
esac

GS_OWNER="`ls -ld $GEMSTONE/seaside/bin | awk '{ print $3 ":" $4 }'`"
chown $GS_OWNER seaside/*
cp -p seaside/* $GEMSTONE/seaside/bin

# Success
exit 0
