#!/bin/bash

if [ $UID -ne 0 ]; then
   echo "You must be root to run this!"
   exit
fi 

### Warning!!! Don't use leading spaces rather than leading tabs in "Here Documents" ###

# Find out where files are located
source config
source $GEMSTONE_CONFIG

echo "`basename $0` creates GemStone/S templates  in $TEMPLATE_DIR for daemontools to"
echo "run worker gems and a maintenance gem. It does not create links in $SERVICE_DIR."

echo "Shall I continue? (Y/N)"

read cont
case "$cont" in
    y|Y|yes)
    ;;
    *)
    echo "Not continuing"
    exit
    ;;
esac

# Create directories expected by daemontools (http://cr.yp.to/daemontools.html)
mkdir -p $TEMPLATE_DIR/gs_maintenance $TEMPLATE_DIR/gs_fastcgi

# Create template for running maintenance gem
cat > $TEMPLATE_DIR/gs_maintenance/run  <<-EOF
	#!/bin/bash
	source /etc/default/gemstone
	source \$GEMSTONE_CONFIG
	\$GEMSTONE/bin/waitstone $GEMSTONE_NAME 2
	exec setuidgid $GEMSTONE_USER \$GEMSTONE/seaside/bin/maintenanceGem30 daemontools
EOF
chmod 755 $TEMPLATE_DIR/gs_maintenance/run

# Create master template for running FastCGI gems
cat > $TEMPLATE_DIR/gs_fastcgi/run  <<-EOF
	#!/bin/bash
	source /etc/default/gemstone
	source \$GEMSTONE_CONFIG
	scriptpath=\$(dirname \$0)
	[ -r \$scriptpath/config.local ] && source \$scriptpath/config.local
	\$GEMSTONE/bin/waitstone $GEMSTONE_NAME 2
	exec setuidgid $GEMSTONE_USER \$GEMSTONE/seaside/bin/seasideGem30 daemon \$GEM_PORT daemontools
EOF
chmod 755 $TEMPLATE_DIR/gs_fastcgi/run

# Create templates to run Seaside gems
for i in `seq $STARTING_PORT $ENDING_PORT` ; do
    # echo "Creating template in $TEMPLATE_DIR/gs_fastcgi-${i}"
    mkdir -p $TEMPLATE_DIR/gs_fastcgi-${i}
    ln -s /etc/sv/gs_fastcgi/run $TEMPLATE_DIR/gs_fastcgi-${i}
    echo "export GEM_PORT=${i}" > $TEMPLATE_DIR/gs_fastcgi-${i}/config.local
    chmod 644 $TEMPLATE_DIR/gs_fastcgi-${i}/config.local
done

echo "Created daemontools templates:"
ls -d $TEMPLATE_DIR/gs_*

# Success
exit 0
