#!/bin/bash

if [ $UID -ne 0 ]; then
   echo "You must be root to run this!"
   exit
fi 

### Warning!!! Don't use leading spaces rather than leading tabs in "Here Documents" ###

# Find out where files are located
source config

echo "`basename $0` links GemStone/S templates for daemontools in $TEMPLATE_DIR to"
echo "the appropriate locations in $SERVICE_DIR. if daemontools is running"
echo "those services will start immediately."

echo "Shall I continue? (Y/N)"

read cont
case "$cont" in
    y|Y|yes)
    ;;
    *)
    echo "Not continuing"
    exit
    ;;
esac

# Create directories expected by daemontools (http://cr.yp.to/daemontools.html)
mkdir -p $SERVICE_DIR 

# Link templates into service directory
ln -s $TEMPLATE_DIR/gs_maintenance $SERVICE_DIR/gs_maintenance
#
for i in `ls -d $TEMPLATE_DIR/gs_seaside-*` ; do
    # echo "Creating service for $i"
    ln -s $i $SERVICE_DIR/
done  

echo "Currently registered daemontools services:"
update-service --list

# Success
exit 0
