#!/bin/bash

if [ $UID -ne 0 ]; then
   echo "You must be root to run this!"
   exit
fi 

### Warning!!! Don't use leading spaces rather than leading tabs in "Here Documents" ###

# Find out where files are located
source config
source $GEMSTONE_CONFIG

echo "`basename $0` creates GemStone templates in $TEMPLATE_DIR for daemontools to run"
echo "Seaside gems, a maintenance gem, and statmons. It does not create links in $SERVICE_DIR."

echo "Shall I continue? (Y/N)"

read cont
case "$cont" in
    y|Y|yes)
    ;;
    *)
    echo "Not continuing"
    exit
    ;;
esac

case "$SEASIDE_VERSION" in
    3.0)
    MAINT_SCRIPT="maintenanceGem30"
    GEM_SCRIPT="seasideGem30"
    # We only need PARAMS because the PORT moved from $1 to $2 in 30
    PARAMS="daemon \\\$GEM_PORT"
    ;;
    2.8)
    MAINT_SCRIPT="maintenanceGem"
    GEM_SCRIPT="seasideGem_FastCGI"
    # We only need PARAMS because the PORT moved from $1 to $2 in 30
    PARAMS="\\\$GEM_PORT"
    ;;
    *)
    echo "SEASIDE_VERSION in the config file is $SEASIDE_VERSION"
    echo "it must be either 3.0 or 2.8"
    ;;
esac

# Create directories expected by daemontools (http://cr.yp.to/daemontools.html)
mkdir -p $TEMPLATE_DIR/gs_maintenance $TEMPLATE_DIR/gstemplate_seaside

# Create template for running maintenance gem
cat > $TEMPLATE_DIR/gs_maintenance/run  <<-EOF
	#!/bin/bash
	source /etc/default/gemstone
	source \$GEMSTONE_CONFIG
	\$GEMSTONE/bin/waitstone $GEMSTONE_NAME 2
	exec setuidgid $GEMSTONE_USER \$GEMSTONE/seaside/bin/$MAINT_SCRIPT
EOF
chmod 755 $TEMPLATE_DIR/gs_maintenance/run

# Create master template for running Seaside gems
cat > $TEMPLATE_DIR/gstemplate_seaside/run  <<-EOF
	#!/bin/bash
	source /etc/default/gemstone
	source \$GEMSTONE_CONFIG
	scriptpath=\$(dirname \$0)
	[ -r \$scriptpath/config.local ] && source \$scriptpath/config.local
	\$GEMSTONE/bin/waitstone $GEMSTONE_NAME 2
	exec setuidgid $GEMSTONE_USER \$GEMSTONE/seaside/bin/$GEM_SCRIPT $PARAMS
EOF
chmod 755 $TEMPLATE_DIR/gstemplate_seaside/run

# Create templates to run Seaside gems
for i in `seq $STARTING_PORT $ENDING_PORT` ; do
    # echo "Creating template in $TEMPLATE_DIR/gs_seaside-${i}"
    mkdir -p $TEMPLATE_DIR/gs_seaside-${i}
    ln -s /etc/sv/gstemplate_seaside/run $TEMPLATE_DIR/gs_seaside-${i}
    echo "export GEM_PORT=${i}" > $TEMPLATE_DIR/gs_seaside-${i}/config.local
    chmod 644 $TEMPLATE_DIR/gs_seaside-${i}/config.local
done  

# Create templates to run a '1-second' and a '60-second' statmon
GS_OWNER="`ls -ld /home/$GEMSTONE_USER | awk '{ print $3 ":" $4 }'`"
for i in 1 60 ; do
    # Rotate '1-second' logs hourly
    HRS="1"
    # Rotate '60-second' logs daily
    [ $i = "60" ] && HRS="24"
    # echo "Creating template in $TEMPLATE_DIR/gs_statmon-${i}"
    mkdir -p $TEMPLATE_DIR/gs_statmon-${i}
    cat > $TEMPLATE_DIR/gs_statmon-${i}/run <<-EOF
	#!/bin/bash
	source /etc/default/gemstone
	source \$GEMSTONE_CONFIG
	mkdir -p /home/$GEMSTONE_USER/stats/${i}-second
	chown -R $GS_OWNER /home/$GEMSTONE_USER/stats
	cd /home/$GEMSTONE_USER/stats/${i}-second
	exec setuidgid $GEMSTONE_USER \$GEMSTONE/bin/statmonitor $GEMSTONE_NAME -r -h $HRS -i ${i} -A -z
	EOF
done

echo "Created daemontools templates:"
ls -d $TEMPLATE_DIR/gs_* $TEMPLATE_DIR/gstemplate_*

# Success
exit 0
