#!/bin/bash

if [ $UID -ne 0 ]; then
   echo "You must be root to run this!"
   exit
fi 

source config
source $GEMSTONE_CONFIG
SEASIDE_BIN=$GEMSTONE/seaside/bin

echo "DANGER: This script removes all GemStone daemontools and boot files"
echo "that were installed by other scripts in this directory. It does not"
echo "stop any running GemStone instances."
echo "Shall I continue? (Y/N)"

read cont
case "$cont" in
    y|Y|yes)
    ;;
    *)
    echo "Not continuing"
    exit
    ;;
esac

# Reset the /etc/issue file to it's Ubuntu default
/etc/init.d/glass_ip_address stop

rm -f /etc/init.d/gemstone /etc/init.d/netldi /etc/init.d/statmon /etc/init.d/topaz
rm -f /etc/init.d/glass_ip_address
rm -f /etc/lighttpd/conf-available/10-GLASS.conf /etc/lighttpd/conf-enabled/10-GLASS.conf
rm -f $SEASIDE_BIN/maintenanceGem $SEASIDE_BIN/maintenanceGem30
rm -f $SEASIDE_BIN/seasideGem30 $SEASIDE_BIN/seasideGem_FastCGI
rm -rf /etc/sv/gstemplate_ /etc/sv/gs_* /etc/service/gs_*
rm -f /etc/rc?.d/*gemstone /etc/rc?.d/*netldi /etc/rc?.d/*statmon /etc/rc?.d/*topaz
rm -f /etc/rc?.d/*glass_ip_address

# Success
exit 0
