#!/bin/bash

if [ $UID -ne 0 ]; then
   echo "You must be root to run this!"
   exit
fi 

# Find out where files are located
source config
source $GEMSTONE_CONFIG

# Infom user what things are running, sleep long enough for daemontools to start processes
$GEMSTONE/bin/gslist -clv
echo ""
svstat $SERVICE_DIR/gs_*

# Success
exit 0
