#!/bin/bash

### BEGIN INIT INFO
# Provides:          gemstone-stone
# Required-Start:    $network
# Required-Stop:     $all
# Default-Start:     3
# Default-Stop:      0 6
# Short-Description: Start and stop Gemstone
# Description:       This script starts and stops a Gemstone stone
### END INIT INFO

. /lib/lsb/init-functions
. /etc/default/rcS

# STARTUP_DEFAULTS must provide $GEMSTONE_CONFIG, the GemStone ENV setup file
STARTUP_DEFAULTS=/etc/default/gemstone

if [ -s $STARTUP_DEFAULTS ]; then
    . $STARTUP_DEFAULTS
    case "x$ENABLED" in
        xtrue|x1|xyes)
                ;;
        *)
                if ! [ "$1" = "stop" ]; then
                    log_failure_msg "Gemstone startup disabled."
                    log_failure_msg "Edit /etc/default/gemstone, set ENABLED=1 to enable Gemstone startup at boot time"
                    exit 1
                fi
                ;;
    esac
else
    log_failure_msg "Configuration file $STARTUP_DEFAULTS not found, aborting startup"
    exit 1
fi
		
if [ -s $GEMSTONE_CONFIG ]; then
    . $GEMSTONE_CONFIG
else
    log_failure_msg "Configuration file $GEMSTONE_CONFIG not found, aborting startup"
    exit 1
fi

export GEMSTONE GEMSTONE_SYS_CONF GEMSTONE_EXE_CONF GEMSTONE_DATADIR GEMSTONE_LOGDIR \
       GEMSTONE_KEYFILE GEMSTONE_NAME PATH MANPATH LD_LIBRARY_PATH


case "$1" in
    start|restart)
            # Attempt to work around startup problems
            sleep 5
            # Change to a writable working directory
            cd /tmp
            # Clear any invalid locks on startup
            $GEMSTONE/bin/gslist -cq > /dev/null
            sudo -E -u $GEMSTONE_USER $GEMSTONE/seaside/bin/startGemstone
            ;;
    stop)
            sudo -E -u $GEMSTONE_USER $GEMSTONE/seaside/bin/stopGemstone
            ;;
    status)
            $GEMSTONE/bin/gslist -clv
            ;;
    *)
            log_success_msg "Usage: /etc/init.d/gemstone (start|stop|restart|status)"
            ;;
esac

