#!/bin/bash

### BEGIN INIT INFO
# Provides:          gemstone-statmon
# Required-Stop:     $all
# Required-Start:    $network gemstone-stone
# Default-Start:     3
# Default-Stop:      0 6
# Short-Description: Start and stop Gemstone statmons
# Description:       This script starts and stops Gemstone statmonitors
### END INIT INFO

. /lib/lsb/init-functions
. /etc/default/rcS

# STARTUP_DEFAULTS must provide $GEMSTONE_CONFIG, the GemStone ENV setup file
# and $SERVICE_DIR, used by daemontools to locate run scripts
STARTUP_DEFAULTS=/etc/default/gemstone

if [ -s $STARTUP_DEFAULTS ]; then
    . $STARTUP_DEFAULTS
    case "x$ENABLED" in
        xtrue|x1|xyes)
                ;;
        *)
                log_failure_msg "Gemstone startup disabled."
                log_failure_msg "Edit /etc/default/gemstone, set ENABLED=1 to enable Gemstone startup at boot time"
                exit 1
                ;;
    esac
else
    log_failure_msg "Configuration file $GEMSTONE_CONFIG not found, aborting startup"
    exit 1
fi

if [ -s $GEMSTONE_CONFIG ]; then
    . $GEMSTONE_CONFIG
else
    log_failure_msg "Configuration file $GEMSTONE_CONFIG not found, aborting startup"
    exit 1
fi

export GEMSTONE GEMSTONE_SYS_CONF GEMSTONE_EXE_CONF GEMSTONE_DATADIR GEMSTONE_LOGDIR \
       GEMSTONE_KEYFILE GEMSTONE_NAME PATH MANPATH LD_LIBRARY_PATH

statmon_start()
{
    # Move to a writable working directory
    cd /tmp

    log_success_msg "Waiting for stone to complete startup..."
    waitstone $GEMSTONE_NAME

    log_success_msg "Starting Statmons..."
    for i in `ls -d $SERVICE_DIR/gs_statmon*`; do
        echo "Starting $i ..."
        svc -u $i
    done
}

statmon_stop()
{
    log_success_msg "Stopping Statmons..."
    for i in `ls -d $SERVICE_DIR/gs_statmon*`; do
        echo "Stopping $i ..."
        svc -d $i
    done
}

statmon_restart()
{
    log_success_msg "Restarting Statmon..."
    statmon_stop
    statmon_start
}

statmon_status()
{
    svstat $SERVICE_DIR/gs_statmon*
}

case "$1" in
    start)
           statmon_start 
            ;;
    restart)
            statmon_restart
            ;;
    stop)
            statmon_stop
            ;;
    status)
            statmon_status
            ;;
    *)
            log_success_msg "Usage: /etc/init.d/statmon (start|stop|restart|status)"
            ;;
esac
